linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - errcheck
    - gosec
    - gocritic
    - prealloc
    - unused

linters-settings:
  gocritic:
    disabled-checks:
      - exitAfterDefer
      - httpNoBody
      - rangeValCopy
      - nestingReduce
  prealloc:
    simple: true
    range-loops: true
    for-loops: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    - path: pkg/cli/
      linters:
        - errcheck
        - unused
    - path: cmd/
      linters:
        - gocritic
    - path: scripts/
      linters:
        - gocritic
        - errcheck
    - path: pkg/binance/client.go
      text: "field .* is unused"
    - path: pkg/metrics/exporter.go
      text: "type name will be used as metrics.MetricsExporter"

  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  tests: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true 