version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - CUSTOM_REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/binance?sslmode=disable
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app
      - go-mod-cache:/go/pkg/mod

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --maxmemory 2gb --maxmemory-policy allkeys-lru

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=binance
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis-viewer:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/app/redis-viewer"]
    environment:
      - CUSTOM_REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

volumes:
  redis-data:
  postgres-data:
  go-mod-cache: 