name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    # Skip if this is a version tag push and we're also pushing to main
    if: |
      !startsWith(github.ref, 'refs/tags/v') ||
      (startsWith(github.ref, 'refs/tags/v') && !contains(github.event.head_commit.message, 'Bump version to'))
    runs-on: ubuntu-22.04
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        check-latest: true
        cache: true

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: go test -v -race ./...

    - name: Run benchmarks
      run: go test -v -run=^$ -bench=. -benchmem ./...

  build:
    name: Build
    needs: test
    runs-on: ubuntu-22.04
    if: |
      github.event_name == 'push' &&
      (
        (github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'Bump version to')) ||
        startsWith(github.ref, 'refs/tags/v')
      )

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        check-latest: true
        cache: true

    - name: Get version
      id: get_version
      run: echo "VERSION=$(cat version.txt)" >> $GITHUB_OUTPUT

    - name: Build
      run: |
        mkdir -p bin
        GOOS=linux GOARCH=amd64 go build -v -ldflags="-X main.Version=$(cat version.txt)" -o bin/streamer-linux-amd64 cmd/streamer/main.go
        GOOS=linux GOARCH=amd64 go build -v -ldflags="-X main.Version=$(cat version.txt)" -o bin/redis-viewer-linux-amd64 scripts/redis-viewer.go
        GOOS=darwin GOARCH=amd64 go build -v -ldflags="-X main.Version=$(cat version.txt)" -o bin/streamer-darwin-amd64 cmd/streamer/main.go
        GOOS=darwin GOARCH=amd64 go build -v -ldflags="-X main.Version=$(cat version.txt)" -o bin/redis-viewer-darwin-amd64 scripts/redis-viewer.go
        tar czf bin/binance-redis-streamer-linux-amd64.tar.gz -C bin streamer-linux-amd64 redis-viewer-linux-amd64
        tar czf bin/binance-redis-streamer-darwin-amd64.tar.gz -C bin streamer-darwin-amd64 redis-viewer-darwin-amd64

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: bin/
        retention-days: 5

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get version
      id: get_version
      run: echo "VERSION=$(cat version.txt)" >> $GITHUB_OUTPUT

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: binaries
        path: bin

    - name: Generate changelog
      id: changelog
      run: |
        PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
        if [ -z "$PREVIOUS_TAG" ]; then
          git log --pretty=format:"* %s" > CHANGELOG.md
        else
          git log --pretty=format:"* %s" $PREVIOUS_TAG..HEAD > CHANGELOG.md
        fi
        echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
        cat CHANGELOG.md >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ steps.get_version.outputs.VERSION }}
        body: ${{ steps.changelog.outputs.CHANGELOG }}
        files: |
          bin/binance-redis-streamer-linux-amd64.tar.gz
          bin/binance-redis-streamer-darwin-amd64.tar.gz
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 