name: Release

on:
  push:
    branches: [ main ]

jobs:
  release:
    name: Test, Build & Release
    runs-on: ubuntu-22.04
    # Skip if it's a release commit
    if: '!contains(github.event.head_commit.message, ''chore(release)'')'
    permissions:
      contents: write
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.5'
          check-latest: true
          cache: true

      - name: Update dependencies
        run: |
          # Update to latest minor versions
          go get -u ./...
          # Ensure we have the latest x/net with security fixes
          go get -u golang.org/x/net
          go mod tidy

      - name: Run tests
        env:
          CUSTOM_REDIS_URL: redis://localhost:6379/0
          TEST_DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db?sslmode=disable
        run: |
          go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          fail_ci_if_error: true

      - name: Generate changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version-file: './project.json'
          version-path: 'version'
          git-message: 'chore(release): {version}'
          output-file: 'CHANGELOG.md'
          skip-version-file: false
          skip-commit: false
          skip-on-empty: false
          git-branch: main

      - name: Build binaries
        run: |
          mkdir -p bin
          # Build Linux binaries
          GOOS=linux GOARCH=amd64 go build -o bin/streamer-linux-amd64 ./cmd/streamer
          GOOS=linux GOARCH=amd64 go build -o bin/redis-viewer-linux-amd64 ./cmd/redis-viewer
          # Build Darwin (macOS) binaries
          GOOS=darwin GOARCH=amd64 go build -o bin/streamer-darwin-amd64 ./cmd/streamer
          GOOS=darwin GOARCH=amd64 go build -o bin/redis-viewer-darwin-amd64 ./cmd/redis-viewer

      - name: Create archives
        run: |
          cd bin
          tar czf binance-redis-streamer-linux-amd64.tar.gz streamer-linux-amd64 redis-viewer-linux-amd64
          tar czf binance-redis-streamer-darwin-amd64.tar.gz streamer-darwin-amd64 redis-viewer-darwin-amd64

      - name: Create Release
        if: steps.changelog.outputs.skipped == 'false'
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.changelog.outputs.tag }}
          tag_name: ${{ steps.changelog.outputs.tag }}
          body_path: CHANGELOG.md
          files: |
            bin/binance-redis-streamer-linux-amd64.tar.gz
            bin/binance-redis-streamer-darwin-amd64.tar.gz
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 