name: Release

on:
  push:
    branches: [ main ]

jobs:
  release:
    name: Test, Build & Release
    runs-on: ubuntu-22.04
    if: ${{ !contains(github.event.head_commit.message, 'chore(release)') }}
    permissions:
      contents: write
      pull-requests: write
      issues: write
      repository-projects: write
      statuses: write
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.5'
          check-latest: true
          cache: true

      - name: Update dependencies
        run: |
          go get -u ./...
          go get -u golang.org/x/net
          go mod tidy

      - name: Run tests
        env:
          CUSTOM_REDIS_URL: redis://localhost:6379/0
          TEST_DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db?sslmode=disable
        run: |
          go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          fail_ci_if_error: true

      - name: Prepare release
        id: prepare_release
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          
          # Get the latest version and bump it
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          LATEST_VERSION=${LATEST_TAG#v}
          
          # Calculate new version based on existing tags
          MAJOR=$(echo $LATEST_VERSION | cut -d. -f1)
          MINOR=$(echo $LATEST_VERSION | cut -d. -f2)
          PATCH=$(echo $LATEST_VERSION | cut -d. -f3)
          
          # Increment patch version
          NEW_VERSION="$MAJOR.$MINOR.$((PATCH + 1))"
          
          # Verify this version doesn't exist
          while git rev-parse "v$NEW_VERSION" >/dev/null 2>&1; do
            PATCH=$((PATCH + 1))
            NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          done
          
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          
          # Make sure we're on a clean state
          git fetch --prune --unshallow
          git checkout -B release/v$NEW_VERSION
          
          # Update project.json
          if [ -f project.json ]; then
            jq ".version = \"$NEW_VERSION\"" project.json > project.json.tmp && mv project.json.tmp project.json
          fi

      - name: Generate changelog
        id: changelog
        run: |
          # Install conventional-changelog-cli
          npm install -g conventional-changelog-cli
          
          # Generate the changelog
          conventional-changelog -p angular -i CHANGELOG.md -s -r 0
          
          # Stage and commit all changes
          git add project.json CHANGELOG.md
          git commit -m "chore(release): v${{ env.NEW_VERSION }}"
          
          # Force push to the release branch
          git push -f origin release/v${{ env.NEW_VERSION }}

      - name: Build binaries
        run: |
          mkdir -p bin
          GOOS=linux GOARCH=amd64 go build -o bin/streamer-linux-amd64 ./cmd/streamer
          GOOS=linux GOARCH=amd64 go build -o bin/redis-viewer-linux-amd64 ./cmd/redis-viewer
          GOOS=darwin GOARCH=amd64 go build -o bin/streamer-darwin-amd64 ./cmd/streamer
          GOOS=darwin GOARCH=amd64 go build -o bin/redis-viewer-darwin-amd64 ./cmd/redis-viewer
          
          cd bin
          tar czf binance-redis-streamer-linux-amd64.tar.gz streamer-linux-amd64 redis-viewer-linux-amd64
          tar czf binance-redis-streamer-darwin-amd64.tar.gz streamer-darwin-amd64 redis-viewer-darwin-amd64

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: "chore(release): v${{ env.NEW_VERSION }}"
          title: "Release v${{ env.NEW_VERSION }}"
          body: |
            Release version ${{ env.NEW_VERSION }}
            
            This PR was automatically created by the release workflow.
            
            Changes included in this release:
            
            ${{ steps.changelog.outputs.clean_changelog }}
          branch: release/v${{ env.NEW_VERSION }}
          base: main
          labels: release
          delete-branch: true

      - name: Create Draft Release
        if: steps.changelog.outputs.skipped == 'false'
        uses: softprops/action-gh-release@v2
        with:
          name: Release v${{ env.NEW_VERSION }}
          tag_name: v${{ env.NEW_VERSION }}
          body_path: CHANGELOG.md
          files: |
            bin/binance-redis-streamer-linux-amd64.tar.gz
            bin/binance-redis-streamer-darwin-amd64.tar.gz
          draft: true
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }} 